#!/usr/bin/env bash

_certhash_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--digest --help" -- "$2"))
    elif [[ $3 = --digest ]]; then
        COMPREPLY=($(compgen -W "sha1 sha512" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _certhash_completion certhash

_enccnf_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--parse --build --remove --digest \
                                 --tftp --certificate --key --help" -- "$2"))
    elif [[ $3 = --digest ]]; then
        COMPREPLY=($(compgen -W "sha1 sha512" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _enccnf_completion enccnf

_mkcert_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--common --organization --unit --locality --state --country \
                                 --years --bits --curve --digest --file --help" -- "$2"))
    elif [[ $3 = --digest ]]; then
        COMPREPLY=($(compgen -W "sha1 sha512" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _mkcert_completion mkcert

_sgnfile_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--parse --build --remove --digest --tftp --help" -- "$2"))
    elif [[ $3 = --digest ]]; then
        COMPREPLY=($(compgen -W "sha1 sha512" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _sgnfile_completion sgnfile

_stripsgn_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _stripsgn_completion stripsgn

_tlvfile_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--parse --build --remove --version --digest --filename \
                                 --sast --ccm --tftp --ccm-tftp --capf --app-server --tvs --help" -- "$2"))
    elif [[ $3 = --digest ]]; then
        COMPREPLY=($(compgen -W "sha1 sha512" -- "$2"))
    elif [[ $3 = --version ]]; then
        COMPREPLY=($(compgen -W "1.0 1.1" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _tlvfile_completion tlvfile
