#!/bin/bash
#
# Copyright (c) 2017-2020 Gareth Palmer <gareth.palmer3@gmail.com>
# This program is free software, distributed under the terms of
# the GNU General Public License Version 2.

OPTIONS=$(getopt -n ${0##*/} -o "c:o:l:s:C:e:a:b:E:y:d:f:H" \
    -l "common:,organization:,locality:,state:,country:,email:,alternate:,bits:,curve:,years:,digest:,output:,help" -- "$@")

if [[ $? -ne 0 ]]; then
    echo "Try '${0##*/} --help' for more information"
    exit 1
fi

eval set -- "$OPTIONS"

COMMON_NAME=""
ORGANIZATION=""
LOCALITY=""
STATE=""
COUNTRY=""
EMAIL_ADDRESS=""
ALTERNATE_NAMES=()
BITS="2048"
CURVE=""
YEARS="10"
DIGEST="sha256"
OUTPUT_FILE=""

while true; do
    OPTION="$1"
    shift 1

    [[ -n $OPTION ]] || break

    case "$OPTION" in
    -c|--common)
        COMMON_NAME="$1"
        shift 1
        ;;
    -O|--organization)
        ORGANIZATION="$1"
        shift 1
        ;;
    -l|--locality)
        LOCALITY="$1"
        shift 1
        ;;
    -s|--state)
        STATE="$1"
        shift 1
        ;;
    -C|--country)
        COUNTRY="${1^^[A-Z]}"
        shift 1

        if [[ ! $COUNTRY =~ ^[A-Z]{2}$ ]]; then
            echo "Invalid country: $COUNTRY" >&2
            exit 1
        fi
        ;;
    -e|--email)
        EMAIL_ADDRESS="$1"
        shift 1

        if [[ ! $EMAIL_ADDRESS =~ ^[a-zA-Z0-9\+\'\.\-]+@([a-zA-Z0-9]+\.)+[a-zA-Z0-9\-]+$ ]]; then
            echo "Invalid email: $EMAIL_ADDRESS" >&2
            exit 1
        fi
        ;;
    -a|--alternate)
        ALTERNATE_NAME="$1"
        shift 1

        if [[ ! $ALTERNATE_NAME =~ ^([a-z0-9\-]+\.)*[a-z0-9\-]+$ ]]; then
            echo "Invalid alternate name: $ALTERNATE_NAME" >&2
            exit 1
        fi

        ALTERNATE_NAMES+=("$1")
        ;;
    -b|--bits)
        BITS="$1"
        shift 1

        if [[ ! $BITS =~ ^[0-9]+$ || $BITS -lt 512 || $BITS -gt 4096 ]]; then
            echo "Invalid bits: $BITS" >&2
            exit 1
        fi
        ;;
    -E|--curve)
        CURVE="$1"
        shift 1
        ;;
    -y|--years)
        YEARS="$1"
        shift 1

        if [[ ! $YEARS =~ ^[0-9]+$ || $YEARS -lt 1 ]]; then
            echo "Invalid years: $YEARS" >&2
            exit 1
        fi
        ;;
    -d|--digest)
        DIGEST="$1"
        shift 1

        if [[ $DIGEST != +(md5|sha1|sha256|sha384|sha512) ]]; then
            echo "Invaid digest: $DIGEST" >&2
            exit 1
        fi
        ;;
    -f|--file)
        OUTPUT_FILE="$1"
        shift 1
        ;;
    -H|--help)
        echo "Usage: ${0##*/} [OPTIONS]"
        echo "Create a self-signed X509 certificate"
        echo ""
        echo "  -c, --common COMMON-NAME           common name"
        echo "  -o, --organization ORGANIZATION    organization"
        echo "  -l, --locality LOCALITY            locality"
        echo "  -s, --state STATE                  state or province"
        echo "  -C, --country COUNTRY              country code"
        echo "  -a, --alternate DNS-NAME           alternate DNS name, can be specified more than once"
        echo "  -e, --email EMAIL                  email address"
        echo "  -y, --years NUMBER                 number of years to sign the certificate (default 10)"
        echo "  -b, --bits NUMBER                  RSA key size (default 2048)"
        echo "  -E, --curve CURVE                  generate an EC key using curve instead of an RSA key"
        echo "  -d, --digest DIGEST                message digest to use: md5, sha1, sha256, sha384 or sha512 (default sha256)"
        echo "  -f, --file                         output file"
        echo "  -h, --help                         print this help and exit"
        echo ""

        exit 0
        ;;
    --)
        shift 1
        break
        ;;
    esac
done

if [[ -z $COMMON_NAME ]]; then
    echo "No common name specified"
    exit 1
fi

if [[ -z $OUTPUT_FILE ]]; then
    OUTPUT_FILE=$(echo "$COMMON_NAME" | sed -e "s/[^A-Za-z0-9\.\-]/_/g").pem
fi

START_DATE=$(date -u -d "now" +"%Y%m%d000000Z")
END_DATE=$(date -u -d "now + $YEARS years" +"%Y%m%d000000Z")

TEMP_DIR=$(mktemp -d /tmp/gencert-XXXXXXXX) || exit 1

trap "rm -rf $TEMP_DIR" EXIT
touch "$TEMP_DIR/random" "$TEMP_DIR/database.txt" "$TEMP_DIR/database.txt.attr"

SERIAL_NUMBER=$(hexdump -n 16 -v -e "1/1 \"%02X\"" /dev/urandom)
echo "$SERIAL_NUMBER" > "$TEMP_DIR/serial.txt"

cat >> "$TEMP_DIR/openssl.cnf" <<EOF
RANDFILE = $TEMP_DIR/random

[ca]
default_ca = ca_default

[ca_default]
new_certs_dir = $TEMP_DIR
database = $TEMP_DIR/database.txt
serial = $TEMP_DIR/serial.txt
default_startdate = $START_DATE
default_enddate = $END_DATE
default_md = $DIGEST
certificate = $TEMP_DIR/crt.pem
private_key = $TEMP_DIR/key.pem
x509_extensions = x509_extensions
policy = policy_default
copy_extensons = none
email_in_dn = yes
preserve = no
unique_subject = no

[x509_extensions]
basicConstraints = CA:true, pathlen:0
keyUsage = Certificate Sign, Digital Signature, Key Encipherment, Data Encipherment
extendedKeyUsage = TLS Web Server Authentication, TLS Web Client Authentication
subjectKeyIdentifier = hash
${ALTERNATE_NAMES[@]:+subjectAltName = @alternate_names}

[policy_default]
commonName = supplied
organizationName = optional
localityName = optional
stateOrProvinceName = optional
countryName = optional
emailAddress = optional

[req]
req_extensions = x509_extensions
distinguished_name = distinguished_name
default_md = $DIGEST
prompt = no

[distinguished_name]
commonName = $COMMON_NAME
${ORGANIZATION:+organizationName = $ORGANIZATION}
${LOCALITY:+localityName = $LOCALITY}
${STATE:+stateOrProviceName = $STATE}
${COUNTRY:+countryName = $COUNTRY}
${EMAIL_ADDRESS:+emailAddress = $EMAIL_ADDRESS}

[alternate_names]
EOF

for (( INDEX=0; INDEX < ${#ALTERNATE_NAMES[@]}; INDEX++ )); do
    echo "DNS.$INDEX = ${ALTERNATE_NAME[$INDEX]}" >> "$TEMP_DIR/openssl.cnf"
done

if [[ -n $CURVE ]]; then
    if ! openssl ecparam -name "$CURVE" -noout 2> /dev/null; then
        echo "Invalid curve: $CURVE"
        exit 1
    fi

    if ! openssl ecparam -name "$CURVE" -genkey -noout \
         -out "$TEMP_DIR/key.pem" 2> /dev/null; then
        echo "Error while generaing EC key"
        exit 1
    fi
else
    if ! openssl genrsa -out "$TEMP_DIR/key.pem" "$BITS" 2> /dev/null; then
        echo "Error while generating RSA key"
        exit 1
    fi
fi

if ! openssl req -config "$TEMP_DIR/openssl.cnf" -new -batch \
     -key "$TEMP_DIR/key.pem" -out "$TEMP_DIR/req.pem"; then
    echo "Error while creating signing request"
    exit 1
fi

if ! openssl ca -config "$TEMP_DIR/openssl.cnf" -notext -selfsign -batch \
     -in "$TEMP_DIR/req.pem" -out "$TEMP_DIR/crt.pem" 2> /dev/null; then
    echo "Error while signing CA certificate"
    exit 1
fi

cat "$TEMP_DIR/key.pem" "$TEMP_DIR/crt.pem" > "$OUTPUT_FILE"
echo "New certificate and private-key saved in $OUTPUT_FILE"

exit 0
