name: shell lint
  
on:
  push:
    branches:
      - master
    paths:
      - mkcert

  pull_request:
    branches:
      - master
    paths:
      - mkcert

jobs:
  lint:
    name: Run shell linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt install shellcheck

      - name: Run shellcheck
        run: |
          shellcheck mkcert
